version: '3.8'

services:
  web-clipboard:
    build: .
    container_name: web-clipboard-app
    ports:
      - "5000:5000"  # Internal port for nginx
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
    restart: unless-stopped
    networks:
      - web-clipboard-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/cleanup"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    container_name: web-clipboard-nginx
    ports:
      - "80:80"
      - "443:443"  # For HTTPS
    volumes:
      - ./nginx/nginx-docker.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs:/var/log/nginx
      # For HTTPS, uncomment and provide SSL certificates:
      # - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - web-clipboard
    restart: unless-stopped
    networks:
      - web-clipboard-network
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  web-clipboard-network:
    driver: bridge

# Optional: Add volume for persistent SSL certificates
# volumes:
#   ssl-certs:
#     driver: local