name: Continuous Integration

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore dependencies
      run: dotnet restore backend/backend.csproj
      
    - name: Build
      run: dotnet build backend/backend.csproj --configuration Release --no-restore
      
    - name: Test Docker build (standard)
      run: docker build -t web-clipboard:test .
      
    - name: Test Docker build (minimal)
      run: docker build -t web-clipboard:minimal -f Dockerfile.minimal .
      
    - name: Test Docker run
      run: |
        docker run -d -p 8080:8080 --name test-container web-clipboard:test
        sleep 10
        curl -f http://localhost:8080 || exit 1
        docker stop test-container
        
  security:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      
    steps:
    - uses: actions/checkout@v4
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
        
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'